version: '3.8'

services:
  db:
    container_name: krowdforce_db
    image: postgres
    restart: always
    ports:
      - 1080:5432
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_krowdforce:/var/lib/postgresql/data
volumes:
  db_data_krowdforce:
